[tool.bumpversion]
current_version = "1.5.1"
commit = true
tag = false
sign_tags = true
tag_name = "{new_version}"
parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(((?P<local>\.dev0\+)([0-9a-fA-F]+)))?'
serialize = [
    "{major}.{minor}.{patch}{local}{utcnow:%Y%m%d%H%M%S}",
    "{major}.{minor}.{patch}",
]

[tool.bumpversion.part.local]
first_value = "valid"
optional_value = "valid"
values = [
    "valid",
    ".dev0+",
]

[tool.bumpversion.file.pyproject.toml]
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
