image: $REPO_URL/stage

services:
  - docker:dind

stages:
  - build
  - test
  - release

default:
  before_script:
    - pip install -q --upgrade pip setuptools
    - pip install -q $END_TO_END_LIB@$CI_COMMIT_REF_NAME || pip install -q $END_TO_END_LIB
    - e2e init

###############################################################
# Build Stage (jobs inside a stage run in parallel)
###############################################################

dev-pypi:
  tags:
    - stage-kube-newer
  stage: build
  before_script:
    - pip3 install -q --upgrade pip build setuptools "twine<6.2" wheel bump-my-version "click<8.3"
    - pip install -q $END_TO_END_LIB@$CI_COMMIT_REF_NAME || pip install -q $END_TO_END_LIB
    - e2e init
  script:
    - bump-my-version bump --no-commit --no-tag dev
    - e2e release --dev --skip-tag

###############################################################
# Test Stage
###############################################################

test-run310:
  tags:
    - stage-kube-newer
  image: python:3.10
  stage: test
  before_script:
    - pip3 install --upgrade pip
  script:
    - pip3 install -r requirements.txt
    - pip3 install .
    - pytest -s -v

test-run311:
  tags:
    - stage-kube-newer
  image: python:3.11
  stage: test
  before_script:
    - pip3 install --upgrade pip
  script:
    - pip3 install -r requirements.txt
    - pip3 install .
    - pytest -s -v

test-run312:
  tags:
    - stage-kube-newer
  image: python:3.12
  stage: test
  before_script:
    - pip3 install --upgrade pip
  script:
    - pip3 install -r requirements.txt
    - pip3 install .
    - pytest -s -v

test-run313:
  tags:
    - stage-kube-newer
  image: python:3.13
  stage: test
  before_script:
    - pip3 install --upgrade pip
  script:
    - pip3 install -r requirements.txt
    - pip3 install .
    - pytest -s -v

test-run314:
  tags:
    - stage-kube-newer
  image: python:3.14
  stage: test
  before_script:
    - pip3 install --upgrade pip
  script:
    - pip3 install -r requirements.txt
    - pip3 install .
    - pytest -s -v
  allow_failure: true

###############################################################
# Release Stage
###############################################################

release-pypi:
  tags:
    - stage-kube-newer
  stage: release
  script:
    # release to internal pypi but do not tag yet
    - e2e release --skip-tag --remote https://github.com/polyswarm/$CI_PROJECT_NAME.git
    # release to public pypi and tag
    - e2e release
      -u $PUBLIC_TWINE_USERNAME
      -p $PUBLIC_TWINE_PASSWORD
      -r $PUBLIC_TWINE_REPOSITORY_URL
      --remote https://github.com/polyswarm/$CI_PROJECT_NAME.git
